baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'


[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Hotels'
    pageRef = '/hotels'
    weight = 20

  [[menus.main]]
    name = 'Contact Us'
    pageRef = '/contact'
    weight = 30

  [[menus.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
